import type { Metadata } from "next";
import { Geist, Geist_Mono, Fraunces, Lora } from "next/font/google";
import Sidebar from "@/components/sidebar";
import MobileMenu from "@/components/mobile-menu";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${fraunces.variable} ${lora.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <MobileMenu />
        <div className="max-w-2xl mx-auto px-4 relative">
          <Sidebar />
          <main className="flex flex-col">{children}</main>
        </div>
      </body>
    </html>
  );
}
